#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py shell -c "from prosud.users.models import User; User.objects.create_superuser('admin', 'test1@t.kz', 'admin')"


/usr/local/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000
